import type { Metadata } from "next";
// --- 1. Import Poppins from Google Fonts ---
import { Poppins } from "next/font/google";
// --- 2. Import Geist fonts from their specific package ---
// Note: The import path below is the official one for Geist
import { GeistSans, GeistMono } from "geist/font";
import { Toaster } from "react-hot-toast";
import "./globals.css";

// Use GeistSans directly from the import (it's already a configured object)
const geistSans = GeistSans;

// Define Poppins correctly (as it IS a Google Font)
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

// Use GeistMono directly from the import
const geistMono = GeistMono;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased `}
      >
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
